// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// twk_version
std::string twk_version();
RcppExport SEXP _rtomahawk_twk_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(twk_version());
    return rcpp_result_gen;
END_RCPP
}
// twk_head
Rcpp::DataFrame twk_head(Rcpp::S4& obj, uint32_t n_records);
RcppExport SEXP _rtomahawk_twk_head(SEXP objSEXP, SEXP n_recordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4& >::type obj(objSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type n_records(n_recordsSEXP);
    rcpp_result_gen = Rcpp::wrap(twk_head(obj, n_records));
    return rcpp_result_gen;
END_RCPP
}
// twk_tail
Rcpp::DataFrame twk_tail(Rcpp::S4& obj);
RcppExport SEXP _rtomahawk_twk_tail(SEXP objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4& >::type obj(objSEXP);
    rcpp_result_gen = Rcpp::wrap(twk_tail(obj));
    return rcpp_result_gen;
END_RCPP
}
// LoadHeader
Rcpp::S4 LoadHeader(std::string input);
RcppExport SEXP _rtomahawk_LoadHeader(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(LoadHeader(input));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rtomahawk_twk_version", (DL_FUNC) &_rtomahawk_twk_version, 0},
    {"_rtomahawk_twk_head", (DL_FUNC) &_rtomahawk_twk_head, 2},
    {"_rtomahawk_twk_tail", (DL_FUNC) &_rtomahawk_twk_tail, 1},
    {"_rtomahawk_LoadHeader", (DL_FUNC) &_rtomahawk_LoadHeader, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rtomahawk(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
