# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

twk_version <- function() {
    .Call(`_rtomahawk_twk_version`)
}

twk_head <- function(obj, n_records) {
    .Call(`_rtomahawk_twk_head`, obj, n_records)
}

twk_tail <- function(obj) {
    .Call(`_rtomahawk_twk_tail`, obj)
}

LoadHeader <- function(input) {
    .Call(`_rtomahawk_LoadHeader`, input)
}

