# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.checkIntervalContig <- function(interval) {
    .Call(`_rtomahawk_CheckIntervalContig`, interval)
}

.checkIntervalContigPosition <- function(interval) {
    .Call(`_rtomahawk_CheckIntervalContigPosition`, interval)
}

.checkIntervalContigRange <- function(interval) {
    .Call(`_rtomahawk_CheckIntervalContigRange`, interval)
}

.checkInterval <- function(interval) {
    .Call(`_rtomahawk_CheckInterval`, interval)
}

.twk_version <- function() {
    .Call(`_rtomahawk_twk_version`)
}

.twk_import <- function(input, output, missingness = 0.95, block_size = 500L, c_level = 1L, filter_univariate = TRUE) {
    .Call(`_rtomahawk_twk_import`, input, output, missingness, block_size, c_level, filter_univariate)
}

.twk_head <- function(obj, n_records) {
    .Call(`_rtomahawk_twk_head`, obj, n_records)
}

.twk_tail <- function(obj, n_records) {
    .Call(`_rtomahawk_twk_tail`, obj, n_records)
}

.OpenTomahawkOutput <- function(input) {
    .Call(`_rtomahawk_OpenTomahawkOutput`, input)
}

.ReadRecordsIntervals <- function(twk, filters, intervals, really = FALSE) {
    .Call(`_rtomahawk_ReadRecordsIntervals`, twk, filters, intervals, really)
}

.ReadRecords <- function(twk, filters, really = FALSE) {
    .Call(`_rtomahawk_ReadRecords`, twk, filters, really)
}

.twk_decay <- function(obj, range, n_bins) {
    .Call(`_rtomahawk_twk_decay`, obj, range, n_bins)
}

.twk_read_aggregate <- function(input) {
    .Call(`_rtomahawk_twk_read_aggregate`, input)
}

.twk_aggregate <- function(twk, agg_name, red_name, xbins, ybins, min_count, threads = 1L, verbose = FALSE, progress = FALSE) {
    .Call(`_rtomahawk_twk_aggregate`, twk, agg_name, red_name, xbins, ybins, min_count, threads, verbose, progress)
}

.twk_scalc <- function(twk, interval, window, minP = 1, minR2 = 0.05, threads = 1L, verbose = FALSE, progress = FALSE) {
    .Call(`_rtomahawk_twk_scalc`, twk, interval, window, minP, minR2, threads, verbose, progress)
}

